language: groovy
jdk: oraclejdk8
sudo: false
branches:
  only:
  - master
addons:
  apt:
    packages:
      - expect
      - lib32z1
      - libstdc++6:i386
env:
  - TERM=dumb # to get clean gradle output
before_install:
  # Install base Android SDK
  - export COMPONENTS=build-tools-24.0.2,android-23,sys-img-armeabi-v7a-android-23,extra-google-m2repository,extra-android-m2repository,extra-android-support
  - export LICENSES="android-sdk-license-c81a61d9"
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS --accept=$LICENSES
  - source ~/.android-sdk-installer/env

  # Create and start emulator
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -memory 512 -wipe-data > emulator.log 2>&1 &
  - adb logcat > logcat.log &
  - wait_for_emulator

script:
- ./gradlew check
- ./gradlew uploadArchives
- ./gradlew --stop
- ./gradlew integTest
after_failure:
  - cat emulator.log
  - cat logcat.log
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
notifications:
  email:
  - fgwei521@gmail.com